CREATE DATABASE IF NOT EXISTS task_manager_mysql
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_0900_ai_ci;

USE task_manager_mysql;

CREATE TABLE IF NOT EXISTS users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL UNIQUE,
	created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL ,
	category_id INT NOT NULL,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(255) NULL,
	is_done TINYINT NOT NULL DEFAULT 0,
    is_deleted TINYINT NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX idx_tasks_is_done_created_at (is_done, created_at),
	CONSTRAINT fk_tasks_user
		FOREIGN KEY (user_id)
		REFERENCES users(id),
	CONSTRAINT fk_tasks_category
		FOREIGN KEY (category_id)
		REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS task_logs (
	id INT PRIMARY KEY AUTO_INCREMENT,
	task_id INT NOT NULL,
	action_type VARCHAR(50) NOT NULL,
   	details VARCHAR(255) NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_task_logs_task
		FOREIGN KEY (task_id)
		REFERENCES tasks(id)
);

